
name: 'Angular Action Update(s)'

on:
  schedule:
    - cron: '30 5 * * 3'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Update ng dependencies'
        uses: fast-facts/ng-update@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: 'main'
          commit-message: 'chore: update dependencies'
          commit-author: 'ng-update[bot] <ng-update[bot]@users.noreply.github.com>'
          


